#!/usr/bin/env python3
"""
Fetch vibe-coded repos from GitHub and merge into projects.json.
Uses gh CLI for authenticated API access.
"""

import json
import subprocess
import time
import re
import sys
from pathlib import Path

EXISTING_PATH = Path(__file__).parent.parent / "data" / "projects.json"

# Search queries to find vibe-coded / AI-built projects
SEARCH_QUERIES = [
    # Direct vibe coding mentions
    "vibe coding",
    "vibe coded",
    "vibe-coded",
    "vibe-coding",
    "vibecoding",
    # Built with AI tools
    "built with cursor",
    "built with claude",
    "built with chatgpt",
    "built with copilot",
    "built with ai",
    "made with cursor",
    "made with claude",
    "made with ai",
    "ai generated app",
    "ai built app",
    "ai coded",
    # Cursor / AI editor mentions in description
    "cursor ai project",
    "claude ai project",
    "generated by ai",
    "coded by ai",
    "prompt engineered",
    # Specific vibe coding tools
    "bolt.new project",
    "v0 dev project",
    "lovable dev",
    "replit agent",
    "devin ai",
    # AI app builders
    "ai webapp",
    "chatgpt clone",
    "ai dashboard",
    "llm app",
    "openai app",
    "langchain app",
    "ai chatbot",
    "ai tool",
    "ai assistant app",
    "gpt wrapper",
    "ai saas",
    "ai starter",
    "nextjs ai",
    "ai template",
    "ai boilerplate",
    # Weekend / hackathon projects (often vibe-coded)
    "hackathon ai project",
    "weekend project ai",
    "side project ai",
    "ai hack",
    "built in a weekend",
    "built overnight",
    "shipped with ai",
    # Specific tech combos common in vibe coding
    "nextjs openai",
    "react openai",
    "streamlit llm",
    "gradio app",
    "chainlit",
    "ai agent framework",
    "autonomous agent",
    "ai workflow",
    "crew ai",
    "autogen project",
]

CATEGORIES_MAP = {
    # Keywords -> category
    "tool": ["tool", "cli", "editor", "ide", "sdk", "library", "framework", "extension", "plugin", "devtool", "developer", "utility", "utilities"],
    "game": ["game", "gaming", "play", "puzzle", "arcade", "rpg", "chess", "trivia", "quiz"],
    "agent": ["agent", "autonomous", "crew", "autogen", "langchain", "langgraph", "llm", "rag", "retrieval", "orchestrat"],
    "api": ["api", "backend", "server", "endpoint", "rest", "graphql", "microservice"],
    "website": ["website", "landing", "portfolio", "blog", "cms", "static"],
    "app": ["app", "dashboard", "saas", "webapp", "platform", "mobile", "ios", "android"],
}

def categorize(name: str, desc: str, topics: list[str]) -> str:
    text = f"{name} {desc} {' '.join(topics)}".lower()
    scores = {}
    for cat, keywords in CATEGORIES_MAP.items():
        scores[cat] = sum(1 for kw in keywords if kw in text)
    best = max(scores, key=scores.get)
    if scores[best] == 0:
        return "other"
    return best

def make_tags(topics: list[str], desc: str) -> list[str]:
    tags = []
    # Use GitHub topics first
    for t in topics[:5]:
        tag = t.lower().replace(" ", "-")
        if len(tag) <= 30:
            tags.append(tag)
    # Add "ai" tag if not present
    if not any("ai" in t for t in tags):
        tags.append("ai")
    if not any("vibe" in t for t in tags):
        tags.append("vibe-coded")
    return tags[:6]

def search_github(query: str, per_page: int = 30) -> list[dict]:
    """Search GitHub repos using gh CLI."""
    try:
        cmd = [
            "gh", "api", "search/repositories",
            "-X", "GET",
            "-f", f"q={query} stars:>2",
            "-f", f"per_page={per_page}",
            "-f", "sort=stars",
            "-f", "order=desc",
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print(f"  [WARN] Query failed: {query}: {result.stderr[:100]}", file=sys.stderr)
            return []
        data = json.loads(result.stdout)
        return data.get("items", [])
    except Exception as e:
        print(f"  [ERR] {query}: {e}", file=sys.stderr)
        return []

def repo_to_project(repo: dict) -> dict:
    """Convert a GitHub API repo object to our project format."""
    name = repo.get("name", "")
    full_name = repo.get("full_name", "")
    desc = repo.get("description") or ""
    topics = repo.get("topics") or []
    owner = repo.get("owner", {})
    stars = repo.get("stargazers_count", 0)
    created = repo.get("created_at", "2025-01-01T00:00:00Z")
    homepage = repo.get("homepage") or ""

    # Clean up name for display
    display_name = name.replace("-", " ").replace("_", " ")
    # Title case but keep short words lowercase
    words = display_name.split()
    display_name = " ".join(
        w if (w.upper() == w and len(w) <= 4) else w.capitalize()
        for w in words
    )

    slug = re.sub(r'[^a-z0-9-]', '-', name.lower())
    slug = re.sub(r'-+', '-', slug).strip('-')

    url = homepage if homepage and homepage.startswith("http") else repo.get("html_url", "")

    return {
        "id": f"gh-{slug}",
        "name": display_name[:50],
        "description": desc[:200] if desc else f"A vibe-coded project by {owner.get('login', 'unknown')}",
        "url": url,
        "builderName": owner.get("login", "unknown"),
        "githubUrl": repo.get("html_url", ""),
        "category": categorize(name, desc, topics),
        "tags": make_tags(topics, desc),
        "submittedAt": created,
        "upvotes": stars,
    }

def main():
    # Load existing projects
    with open(EXISTING_PATH) as f:
        existing = json.load(f)

    existing_ids = {p["id"] for p in existing}
    existing_github_urls = {p.get("githubUrl", "").rstrip("/").lower() for p in existing if p.get("githubUrl")}
    existing_names = {p["name"].lower() for p in existing}

    all_repos = {}  # full_name -> repo dict

    total_queries = len(SEARCH_QUERIES)
    for i, query in enumerate(SEARCH_QUERIES):
        print(f"[{i+1}/{total_queries}] Searching: {query}", file=sys.stderr)
        repos = search_github(query, per_page=30)
        for repo in repos:
            fn = repo.get("full_name", "")
            if fn and fn not in all_repos:
                all_repos[fn] = repo
        # Rate limit: GitHub allows 30 requests/min for search
        if i < total_queries - 1:
            time.sleep(2.5)

    print(f"\nTotal unique repos found: {len(all_repos)}", file=sys.stderr)

    # Convert and deduplicate
    new_projects = []
    for fn, repo in all_repos.items():
        proj = repo_to_project(repo)

        # Skip if already exists
        github_url = proj.get("githubUrl", "").rstrip("/").lower()
        if proj["id"] in existing_ids:
            continue
        if github_url and github_url in existing_github_urls:
            continue
        if proj["name"].lower() in existing_names:
            continue

        # Skip forks and very low quality
        if repo.get("fork"):
            continue
        if repo.get("stargazers_count", 0) < 3:
            continue
        if not repo.get("description"):
            continue

        new_projects.append(proj)

    # Sort by stars descending
    new_projects.sort(key=lambda p: p["upvotes"], reverse=True)

    # Take enough to reach ~1000 total
    needed = max(0, 1000 - len(existing))
    new_projects = new_projects[:needed]

    print(f"Adding {len(new_projects)} new projects (existing: {len(existing)})", file=sys.stderr)
    print(f"New total: {len(existing) + len(new_projects)}", file=sys.stderr)

    # Merge
    merged = existing + new_projects

    # Write output
    with open(EXISTING_PATH, "w") as f:
        json.dump(merged, f, indent=2, ensure_ascii=False)

    print(f"Written {len(merged)} projects to {EXISTING_PATH}", file=sys.stderr)

if __name__ == "__main__":
    main()
